server:
  servlet:
    context-path: /hello-spring
  port: 5454

spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/spring_tutorial"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: '1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij'
  valid-duration: 86400
  refreshable-duration: 2592000