server:
  servlet:
    context-path: /hello-spring
  port: 5454

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/spring_tutorial"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true